export CUDA_VISIBLE_DEVICES=4,5,6,7
export N_GPUS=4
export BASE_MODEL="/oss/public/user/wangziyan/models--Qwen--Qwen2.5-3B/snapshots/3aab1f1954e9cc14eb9509a215f9e5ca08227a9b"
# export DATA_DIR="/oss/public/user/wangziyan/ziyan_data/tinyzero_data/countdown"
export DATA_DIR="/oss/public/user/wangziyan/ziyan_data/gsm8k"
# export DATA_DIR="/oss/public/user/wangziyan/ziyan_data/MATH"
export ROLLOUT_TP_SIZE=2
export EXPERIMENT_NAME=gsm8k-qwen2.5-3b_lookahead_len2048
export VLLM_ATTENTION_BACKEND=XFORMERS
CKPT_PATH=/oss/public/user/wangziyan/ziyan_tinyZero
PROJECT_NAME=lookahead_tinyzero

CUDA_VISIBLE_DEVICES=4,5,6,7 python3 -m verl.trainer.main_ppo \
algorithm.adv_estimator=grpo \
data.train_files=$DATA_DIR/train.parquet \
data.val_files=$DATA_DIR/test.parquet \
data.train_batch_size=256 \
data.val_batch_size=512 \
data.max_prompt_length=256 \
data.max_response_length=2048 \
actor_rollout_ref.model.path=$BASE_MODEL \
actor_rollout_ref.actor.entropy_coeff=0.0001 \
actor_rollout_ref.actor.use_kl_loss=True \
actor_rollout_ref.actor.optim.lr=1e-6 \
actor_rollout_ref.actor.ppo_mini_batch_size=128 \
actor_rollout_ref.actor.ppo_micro_batch_size=8 \
actor_rollout_ref.rollout.log_prob_micro_batch_size=8 \
actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP_SIZE \
actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
actor_rollout_ref.ref.log_prob_micro_batch_size=4 \
algorithm.kl_ctrl.kl_coef=0 \
trainer.logger=['wandb'] \
+trainer.val_before_train=False \
trainer.default_hdfs_dir=null \
trainer.n_gpus_per_node=$N_GPUS \
trainer.nnodes=1 \
trainer.save_freq=100 \
trainer.test_freq=100 \
trainer.project_name=$PROJECT_NAME \
trainer.experiment_name=$EXPERIMENT_NAME \
trainer.default_local_dir=$CKPT_PATH/$PROJECT_NAME/$EXPERIMENT_NAME \
+actor.use_lookahead=True \
+actor_rollout_ref.lookahead_inner_steps=3 \
+actor_rollout_ref.lookahead_step_size=0.2 \
trainer.total_epochs=40 2>&1 | tee verl_demo.log 